RATE: 3600
ROUTE_FILE_PREFIX: "map2_3lane_norm_demo"
ROUTE_FILE: "map2_3lane_norm_demo_rate3600.rou.xml"
SCENARIO_DIR: "scenarios/real_world2"
SUMO_CONFIG: "map2_3lane_norm.sumocfg"
NETWORK_FILE: "map2_3lane_norm.net.xml"
ACTION_SPACE: "three_lane_8"
USE_GUI: true
GUI_SETTINGS_FILE: "configs/demo_gui_settings_norm.xml"
GUI_DELAY_MS: 0
GUI_WINDOW_TITLE: "real_world2 normalized | fixed-time"
RENDER_STRESS: true
REGENERATE_ROUTES: false
RUN_SINGLE_DEMO: true
CONTINUE_DEMO_AFTER_SUCCESS: true
RUN_TRAINING: false
RUN_EVALUATION: false
LOAD_WEIGHTS_FOR_EVALUATION: false
RESULTS_DIR: "../../outputs/runs/demo_real_world2_norm_fixed_time"
RANDOM_SEED: 7
DEMO_SEED: 20007
DEMO_CONTROLLER: "fixed_time_rr"
DEMO_INCIDENT_EDGES: ["R00055_cluster_2487953928_3333093993_3333242895_3333242896__8more_cluster_2487953929_3333093994_3333227776_3333227777__8more", "R00055_cluster_2487953929_3333093994_3333227776_3333227777__8more_cluster_2487953928_3333093993_3333242895_3333242896__8more"]
TIME: 4000
INCIDENT_TIME: 400
BASELINE_WARMUP_TIME: 60.0
DECISION_INTERVAL: 10
TAU: 1.1
DECISION_ORDER_STRATEGY: "checkerboard"
ALLOW_NEIGHBOR_INFO: true
ADP_VARIANT_LABEL: "demo_real_world2_norm_fixed_time"
